package midterm;
import simView.*;
import java.awt.*;

public class ef extends ViewableDigraph
{
	
	public ef()
	{
		this("ef", 10, 20);
	}
	
	public ef(String name, double processing_t, double processing_t2)
	{
		super(name);
		
		addInport("in"); 
		addOutport("out");
		
		ViewableAtomic p = new proc("p", processing_t);
		ViewableAtomic p2 = new proc2("p2", processing_t2);

		add(p);
		add(p2);

		
		addCoupling(p, "out", p2, "in");
		
		addCoupling(p2, "out", this, "out");
		addCoupling(this,"in",p,"in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(452, 376);
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(149, 26));
        ((ViewableComponent)withName("p2")).setPreferredLocation(new Point(144, 195));
    }
}
