package midterm;
import java.awt.*;
import simView.*;

public class efp extends ViewableDigraph 
{

	public efp()
	{
		super("efp");
		
		ViewableAtomic g = new genr("g", 40);
		ViewableDigraph  expf = new ef("ExpFrame", 10, 20);

		add(expf);
		add(g);

		addCoupling(expf, "out", g, "in");

		addCoupling(g, "out", expf, "in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(980, 644);
        ((ViewableComponent)withName("ExpFrame")).setPreferredLocation(new Point(359, 186));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(106, 238));
    }
 }
